#!/bin/bash
#SBATCH --job-name=BC_unicyc
#SBATCH --partition=covid
#SBATCH --qos=covid
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=25
#SBATCH --time=12:30:00
#SBATCH --mem=90000


#module load Unicycler
conda activate unicycler
unicycler -t 25  --min_fasta_length 500 -1 trimmed/seq-nd-Bc-511999-22_12m_S40_trimm_1.fastq.gz -2 trimmed/seq-nd-Bc-511999-22_12m_S40_trimm_2.fastq.gz -l all_RNAspades/transcripts_1_100K.fasta  -o all_RNA_1_100K_unicycler 2>> uni_err.log >> uni_stdout.log
