## slurm cluster details
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time_long}
    --job-name=smk-{rule}
#    --output=logs/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - partition=covid
  - qos=covid
  - mem_mb=10000
  - time_long="04:00:00"
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 4
cores: 120
latency-wait: 60
jobs: 25
keep-going: True
rerun-incomplete: True
printshellcmds: True
